#!/bin/sh /etc/rc.common

START=99
STOP=15

EXTRA_COMMANDS="status"
EXTRA_HELP="        status          Check service status"

start() {
    echo "Starting TollGate whoami"/whoami.log 2>&1
    /root/whoami >> /tmp/whoami.log 2>&1 &
    echo "PID: $!" >> /tmp/whoami.log 2>&1
}

stop() {
    echo "Stopping TollGate whoami"
    killall whoami
}

status() {
    if pgrep -f "/root/whoami" >/dev/null; then
        echo "TollGate whoami is running"
        return 0
    else
        echo "TollGate whoami is not running"
        return 1
    fi
}
