# .github/workflows/update-release-json.yml in tollgate-os
name: Update Release JSON

on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/update-release-json.yml'
      - 'actions/update-release-json/**'
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID of the build workflow'
        required: true
  repository_dispatch:
    types: [update-release-json]

# Add permissions block here
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: develop
          token: ${{ secrets.REPOSCOPE }}
          clean: true
          persist-credentials: false
          fetch-depth: 0

      - name: Download SDK Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.client_payload.sdk_run_id }}
          repo: OpenTollGate/tollgate-sdk
          github_token: ${{ secrets.REPOSCOPE }}
          path: sdk-artifacts
          check_artifacts: true
          # Use the array directly without fromJson()
          name: ${{ join(github.event.client_payload.artifacts, ',') }}

      - name: Process Real Events
        run: |
          echo "Real artifacts downloaded:"
          find sdk-artifacts -type f | sort
          # Verify NIP-94 event files exist
          if [ $(find sdk-artifacts -name '*-event.json' | wc -l) -eq 0 ]; then
            echo "::error::No NIP-94 event files found!"
            exit 1
          fi

      - name: Update Release JSON
        uses: ./actions/update-release-json
        with:
          artifacts_path: sdk-artifacts  # Changed from artifacts
          release_json_path: release.json
          target_branch: develop
          github_token: ${{ secrets.REPOSCOPE }}
          commit_message: "Update release.json with real NIP-94 events [skip ci]"

      - name: Debug Incoming Payload
        run: |
          echo "Full event payload:"
          echo '${{ toJSON(github.event) }}' | jq .
          
          echo "Client payload contents:"
          echo '${{ toJSON(github.event.client_payload) }}' | jq .
          
          echo "NIP-94 events data:"
          echo '${{ toJSON(github.event.client_payload.nip94_events) }}' | jq .
          
          # Write to a file for validation
          mkdir -p debug
          echo '${{ toJSON(github.event.client_payload.nip94_events) }}' > debug/received_events.json
          echo "Stored events in debug/received_events.json"

      - name: Validate Event Structure
        run: |
          if [ ! -s "debug/received_events.json" ]; then
            echo "::error::No events data received!"
            exit 1
          fi
          
          # Validate JSON structure
          if ! jq empty debug/received_events.json; then
            echo "::error::Invalid JSON structure in received events"
            jq . debug/received_events.json
            exit 1
          fi
          
          # Check for at least one event
          EVENT_COUNT=$(jq '.events | length' debug/received_events.json)
          if [ "$EVENT_COUNT" -eq 0 ]; then
            echo "::warning::Received empty events array"
          else
            echo "Received $EVENT_COUNT valid NIP-94 events"
          fi